### ISSUE TITLE
upgrade simple-commit-message to 3.x.x

### ISSUE THREAD

**Issue by AVVS** [bahmutov/pre-git#109]
Please do either that, or allow loading own modules for checking commit-message

Thanks!

**Comment by bahmutov** [comment]
Version `3.15.1` has been published to NPM. The full release note can be found at [pre-git/releases/tag/v3.15.1](https://github.com/bahmutov/pre-git/releases/tag/v3.15.1).

**Tip:** safely upgrade dependency pre-git in your project using [next-update](https://github.com/bahmutov/next-update)
