### ISSUE TITLE
Living on it's own!

### ISSUE THREAD

**Issue by lirantal** [bahmutov/pre-git#114]
Nice stuff @bahmutov, thanks!

I'm wondering if you considered making pre-git it's own repo? the fact that it's forked hinders on some things like the inability to search the code-base etc.

**Comment by bahmutov** [comment]
Yes it is time, you are right about it. Will do.

**Comment by lirantal** [comment]
Awesome!
I'd love to help out with some stuff there so once you go mint I'll open some issues/PRs :-)

**Comment by bahmutov** [comment]
Done, the repo has been separated from the original

**Comment by lirantal** [comment]
yay :-)
