### ISSUE TITLE
No colors in command output

### ISSUE THREAD

**Issue by IcanDivideBy0** [bahmutov/pre-git#22]
When using pre-commit/push commands that produces colored output, the colors aren't shown in hook output. Also, all the hook output seems to be sent to the terminal at the end of the execution. Do you think it is possible to use streams for command runner [here](https://github.com/bahmutov/pre-git/blob/master/hooks/pre-common.js#L140-L152)?

**Comment by lillem4n** [comment]
:+1:

**Comment by bahmutov** [comment]
Fixed, same as #29

**Comment by lillem4n** [comment]
:+1: again :)
