### ISSUE TITLE
Erro ao instalar o hook

### ISSUE THREAD

**Issue by dflourusso** [bahmutov/pre-git#23]
Se o hook **pre-commit** não existir por exemplo ele dá erro na instalação em vez de criar o arquivo.

**Comment by bahmutov** [comment]
if pre-commit hook does not exists the installation fails instead of creating the file

**Comment by bahmutov** [comment]
Could you recreate the bug. I just did with latest pre-git, it creates the hooks folder and files

**Comment by dflourusso** [comment]
I installed again and now it appears ok, thanks
