### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by alessioalex** [bahmutov/pre-git#31]
pre-push Nothing to pre- test. Bailing out.

Scripts property:

    "pre-push": [ "node -e 'throw new Error('damn');" ]

**Comment by bahmutov** [comment]
Hi, usually when it says nothing to `pre-test` is because you don't have no local commits to be pushed to the remote repository. Could you confirm that you have local commits?

**Comment by lillem4n** [comment]
There is also an issue with one to many ':s

**Comment by bahmutov** [comment]
yeah, will close for now
