### ISSUE TITLE
package.json in a different folder 

### ISSUE THREAD

**Issue by killanaca** [bahmutov/pre-git#34]
hi
it's possible to support a package.json file in a folder different from the folder that contains .git?
something like this:

.git
extra
project_one/package.json
project_two
lib

Because at the moment when i run git commit from the root folder, pre-common.js fails with this message:
pre-commit An Error was thrown: RangeError: Maximum call stack size exceeded
(it cant find package.json in project_one i suppose)

thanks

**Comment by bahmutov** [comment]
Hmm, very weird case, why would you have multiple package files in single repo? And where should it look for the package.json in this case? In any case, I tried to make `pre-git@1.2.2` more robust and give meaningful error in this case.

**Comment by killanaca** [comment]
The case is for example a little more complex project, when there isn't only the web but also application console for example. Something like this:

.git
project_cli_1/
project_cli_2/package.json
project_web_/package.json

it would be possible to get the path where i run the git command and use that package.json?

thanks a lot
