### ISSUE TITLE
Hooks shebang broken

### ISSUE THREAD

**Issue by grit96** [bahmutov/pre-git#63]
The node shebang in the hook files causes an error with /usr/bin/env:
```
/usr/bin/env: node --harmony: No such file or directory
````
It's because the command gets treated as this: `$ /usr/bin/env "node --harmony"` which will fail, whereas `$ /usr/bin/env node --harmony` does not.

A better way would be to call the JS files from the hooks with `/usr/bin/env node --harmony` prefixed, and remove the shebang from the JS files.

**Comment by bahmutov** [comment]
merged the pull request again, hope 2nd time is the charm. Thanks again for noticing the problem!
