### ISSUE TITLE
Add ybiquitous  as collaborator

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/pre-git#76]
Hi @ybiquitous ! 

You did such nice job resolving your own (plus others') issue, I wanted to add you as a collaborator!

By pushing code, it should publish new versions automatically, as long as you use commit message convention.

Thank you for your contribution,

**Comment by ybiquitous** [comment]
OK!  I want to participate! :smile:

**Comment by bahmutov** [comment]
cool! you should have full right to the repo now, and the publish process is simple - just push and if the unit tests on travis CI pass, then semantic-release publishes it

**Comment by bahmutov** [comment]
BTW, I will add you to the list of collaborators
