### ISSUE TITLE
Plese inform developer install node modules if node_modules empty http://i.imgur.com/pwgAmtg.png

### ISSUE THREAD

**Issue by san4osq** [bahmutov/pre-git#81]
Plese inform developer install node modules if node_modules empty http://i.imgur.com/pwgAmtg.png

**Comment by bahmutov** [comment]
So this situation happens when
- you pull new project from remote repo
- try to commit right away 
- the hook in .git folder tries to use ./node_modules/... but the `pre-git` module has not been installed yet

**Comment by bahmutov** [comment]
One just needs to put hooks from this projects into fresh git repo's .git folder to test this

**Comment by bahmutov** [comment]
Best way to recreate the problem
- clone this repo and run `npm install`
- execute `npm run e2e` which goes through the script `test/e2e.sh` and creates
a new test folder inside `/tmp/test-pre-git` folder
- cd `/tmp/test-pre-git` folder and remove `node_modules` folder
- try making an empty commit `git commit --allow-empty -m "test"`
you should see the problem - tries to use node modules folder and fails
```
.git/hooks/pre-commit: line 3: ./node_modules/.bin/pre-commit: No such file or directory
```

**Comment by san4osq** [comment]
Can you add error message if nodejs modules not installed?
Example:
```
Please install node modules 
`npm install`
```

**Comment by bahmutov** [comment]
Would you like to implement this and add to all hook files and submit a pull request? Will gladly accept it!

**Comment by san4osq** [comment]
I dont know what I need to do
