### ISSUE TITLE
node_modules in subfolder

### ISSUE THREAD

**Issue by tamascsaba** [bahmutov/pre-git#84]
Cannot find node_modules folder, please run 'npm install' first
.git/hooks/pre-commit: 6: exit: Illegal number: -1

**Comment by bahmutov** [comment]
What's the project's structure in your case?

**Comment by tamascsaba** [comment]
Like this and more package.json has own pre-git config :)
```
.
|____.git
|____modules
| |____foo
| | |____package.json
| |____bar
| | |____src
| | |____package.json
```

**Comment by bahmutov** [comment]
ohhhh, can I ask why people do this? Why not separate modules?

**Comment by tamascsaba** [comment]
because it is really small modules and easiest to version control

**Comment by bahmutov** [comment]
fair point, but then the question is where do you install `pre-git` ?

**Comment by tamascsaba** [comment]
Nice idea :) i install create a package.json in base folder, that only dependency is pre-git.

Thanks :+1:
