### ISSUE TITLE
Add check for untracked files

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/pre-git#89]
My common mistake is not adding a file. Local tests pass, while remote fail.
It would be nice to have pre-commit hook that would check if there are untracked files and would stop the commit.

**Comment by xt0rted** [comment]
I just updated from v3.8.4 to v3.9.1 and this broke my development process. Can this be turned off at all?

**Comment by bahmutov** [comment]
Not, but if you add this as an option in package json to turn it off when needed, I would merge it in quickly
