### ISSUE TITLE
Tests fail with pre-commit still allows commit to pass

### ISSUE THREAD

**Issue by asavin** [bahmutov/pre-git#90]
This might not be an issue with `pre-git`, but somehow when I run `npm test` as part of pre-commit hook (defined in `package.json`) and tests fail, commit is still allowed to pass through.

<img width="363" alt="alex_badgeras____red-badger_website-next-2_website-next__zsh_" src="https://cloud.githubusercontent.com/assets/487468/16083103/b6a0c31e-330b-11e6-80ce-ae6384a39c5e.png">

My pre-git config part of `package.json` looks like this:

````
 "config": {
    "pre-git": {
      "pre-commit": [
        "npm t"
      ],
      "pre-push": [],
      "post-commit": [],
      "post-checkout": [],
      "post-merge": []
    }
  }

**Comment by bahmutov** [comment]
hmm, that should not happen. Can I ask which version of pre-git you are rocking?

**Comment by asavin** [comment]
It's `3.9.0`

**Comment by bahmutov** [comment]
Will investigate, thank you for opening an issue

**Comment by asavin** [comment]
That was quick, thanks! All work now.
