### ISSUE TITLE
Cannot push after installing ver. 3.10.0

### ISSUE THREAD

**Issue by voroshkov** [bahmutov/pre-git#95]
Cannot "git push" after updating from 1.4.0 to 3.10.0 on Windows.

Getting the following error:

```
git ls-remote failed
pre-push Check went wrong.
pre-push { [Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "git ls-remote --heads origin test-br"
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
]
  killed: false,
  code: 128,
  signal: null,
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe /s /c "git ls-remote --heads origin test-br"' }
error: failed to push some refs to 'git@github.com:<my_repo_name>'
```

I'm using the following config in package.json:

```
"config": {
    "pre-git": {
      "commit-msg": "conventional",
      "msg-pattern": "chore:.*|.*IPLNSCRD-\\d{3,}.*",
      "pre-commit": [],
      "pre-push": [],
      "post-commit": [],
      "post-merge": []
    }
  }
```

**Comment by bahmutov** [comment]
Are you sure this is due to pre-git and not general remote server? Can you skip the hook using `--no-verify` option?

**Comment by voroshkov** [comment]
I had set the config as described above, then completely removed git hooks from .git folder in local repo, then ran ```npm install```. And this led me to error upon pushing.
Then I replaced version to 1.4.0 in package.json and ran ```npm install``` again. Hooks got updated and pushing worked fine.

Haven't tried to skip the hook though.

**Comment by voroshkov** [comment]
I've just tested omitting the hook using ```--no-verify``` in 3.10.0  - it pushes fine.

**Comment by voroshkov** [comment]
Ok, thanks for your reply. Will try to debug.

**Comment by Ripley511** [comment]
Hi voroshkov,
I ran into the exact same problem using v3.11, I am under the impression that you need credentials to execute the `git ls-remote` command, but these are not included when running the command from pre-push.js
Were you able to solve this bug?

**Comment by voroshkov** [comment]
@Ripley511, unfortunately I couldn't  dig deep enough to solve it. Just reverted to using the older version.

**Comment by Ripley511** [comment]
Just edited my comment with a possible answer, sorry I did not write AFTER debugging ^^

**Comment by voroshkov** [comment]
Oh, I see, thanks! Indeed I've set up git to always ask for credentials.
