### ISSUE TITLE
Add a way to disable default behaviors 

### ISSUE THREAD

**Issue by bratanon** [bahmutov/pre-git#96]
This module make assumptions that everyone that installs it want the predefined behaviors in _pre-commit.js_ and _pre-push.js_. 

I would find it very good if these predefined behaviors was optional and could be enabled/disabled from the _package.js_ config.

**Comment by bahmutov** [comment]
hmm, I see your point, a flag like this would be useful to disable the hooks
```json
{
"config": {
  "pre-git": {
     "enabled": false
  }
}
```

**Comment by bahmutov** [comment]
Should be under version 3.11.0
Thanks for the suggestion

**Comment by bratanon** [comment]
This new thing does not make sense as it will disabled the whole module as I understand it.
What I ment is the default behaviours in each of the mentioned hooks.

For example _bin/pre-commit.js_ is by default first calling `haveChangesToCommi()t`. That is the default behaviour I'm talking about. 

The same goes for _bin/pre-push.js_, it is calling `haveCommitsToPush()` the first thing.

A solution could be that those files have a condition whether or not to use the predefined behaviour or not. 

```
{
"config": {
  "pre-git": {
     "pre-push-use-defaults": false
     "pre-push": []
  }
}
```

Then something like 

```
const preGit = require('pre-git');
const config = preGit.getConfig();
...

...
if (config[pre-push-use-defaults])  {
  runTask((err) => {})
    .then(...
    ...
} else {
  haveCommitsToPush()
    .then(runTask, (err) => {
    ...
}
```

**Comment by bahmutov** [comment]
Well, in this case the initial issue was unclear, but your code contributions would be welcome!

**Comment by bahmutov** [comment]
Hmm, yeah, this could be skipped per hook basis using command line options, plus you can always edit the tasks themselves to skip them?

**Comment by bratanon** [comment]
> this could be skipped per hook basis using command line options
How?

> you can always edit the tasks themselves to skip them
If I'm the only one using them, correct. But when there are more the one contributor that will not work as then every contributor must edit them.
