### ISSUE TITLE
Why enabled is false by default?

### ISSUE THREAD

**Issue by neiker** [bahmutov/pre-git#97]
I think it has no sense. You need to add `"enabled": true,` when update to last version.

**Comment by bahmutov** [comment]
Good catch, should be enabled by default for old configs. Probably will invert to negative "skipHooks" option instead

**Comment by neiker** [comment]
Here's the problem https://github.com/bahmutov/pre-git/blob/master/src/pre-git.js#L151

I'll make a PR later fixin it

**Comment by bahmutov** [comment]
already done, hold on
